name: go-test
on:
  push:
  pull_request:
  schedule:
    - cron: '12 4 20 * *'

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.13', '1.14', '1.15', '1.16']

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: go test -v ./...
